### ISSUE TITLE
cannot find package "github.com/alexeysoshin/smali2java/parser"

### ISSUE THREAD

**Issue by leagmain** [AlexeySoshin/smali2java#1]
go build error:
smali2java.go:6:2: cannot find package "github.com/alexeysoshin/smali2java/parser" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/alexeysoshin/smali2java/parser (from $GOROOT)
	/Users/leagmain/go/src/github.com/alexeysoshin/smali2java/parser (from $GOPATH)

**Comment by AlexeySoshin** [comment]
Probably you cloned it not to GOPATH, but somewhere else.

Make sure that you put it there:
`/Users/leagmain/go/src/github.com/alexeysoshin/smali2java`
