### ISSUE TITLE
Explain purpose of binary files

### ISSUE THREAD

**Issue by DanDevine** [AlexeySoshin/smali2java#25]
After I used this project, my security scanner identified one of the binary files as containing a malicious script.
It found that  **smali2java_windows_amd64.exe** contained the **Trojan_Shelma.geq** script.

This may be incorrect, or your build machine may be infected.  Please comment on the need for the binary files, why they're included, and if you can confirm/deny my scanner results?

Thanks,
DD

**Comment by AlexeySoshin** [comment]
The binary files are for people that don't have Go compiler, and still would like to run the project locally.

The binaries are built from exactly the same source, and don't contain any viruses. 

If you're still uncertain, you can build those binaries yourself..
